on: 
  workflow_dispatch:
    inputs:
      device:
        description: 'Select device'     
        required: true
        type: choice
        options:
        - AXT1800
        - SF1200
        - SFT1200
      email:
        description: 'Git accuont email address'  
        required: false
      gituser:
        description: 'Git user name'  
        required: false
        
jobs:
  setpackage:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: build ipk
      id: build
      env:
        BOARD: ${{ github.event.inputs.device }}
        EMAIL: ${{ github.event.inputs.email }}
        GIT_USER: ${{ github.event.inputs.gituser }}
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ./build.sh
        ./build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: Related_ipks
        path: |
          ./*ipk*
